In [ ]:
#4.1
#1
import numpy as np
empty_array = np.empty((2,2))
print("Empty array: ",empty_array)


Empty array:  [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [ ]:
#2
import numpy as np
one_array= np.full((4,2),fill_value=1)
print(one_array)


[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
#3
import numpy as np
import numpy as np
array_full = np.full((3, 3), fill_value=14)

print(array_full)



[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [ ]:
#4
import numpy as np
given_array=np.array([[2,3,4],[7,6,5]])
zeros_array=np.zeros_like(given_array)
print(zeros_array)


[[0 0 0]
 [0 0 0]]


In [ ]:
#5
import numpy as np
given_array= np.array([[1,2,3], [4,5,6]])
ones_array= np.ones_like(given_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
#6
import numpy as np
new_list=[1,2,3,4]
array= np.array(new_list)
print(array)

[1 2 3 4]


In [ ]:
#4.1.1
#1
import numpy as np

arr1=np.arange(10,49)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#2
import numpy as np
arr1=np.arange(9)
arr2=arr1.reshape(3,3)
print(arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3
import numpy as np
arr1=np.eye(3,3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
import numpy as np
array= np.random.random(30)
mean= array.mean()
print("Random array: ",array)
print("Mean: ",mean)


Random array:  [0.04841277 0.02199967 0.01278067 0.35741835 0.8907592  0.78424963
 0.78699613 0.63671278 0.97801603 0.73727593 0.89425892 0.66769811
 0.08021888 0.07886388 0.08748515 0.42306122 0.17258258 0.39870858
 0.53117089 0.92370424 0.13188255 0.00217589 0.99585807 0.90619236
 0.02735881 0.2599546  0.53743749 0.5573946  0.60259822 0.87505731]
Mean:  0.48027611687093813


In [ ]:
#5
import numpy as np
array1= np.random.random((10,10))

max=np.max(array1)
min=np.min(array1)
print("Maximum: ",max)
print("Minimum: ",min)

Maximum:  0.995838900343062
Minimum:  0.010046607198232138


In [ ]:
#6
import numpy as np
#zero array of size 10
array = np.zeros(10)
#replacing 5th element whose index number is 4 with 1
array[4]=1
print(array)

In [ ]:
#7
import numpy as np
array = np.array([1,2,0,0,4,0])
reversed_arr= array[::-1]
print("Original array: ",array)
print("Reversed array: ",reversed_arr)


Original array:  [1 2 0 0 4 0]
Reversed array:  [0 4 0 0 2 1]


In [ ]:
#8
import numpy as np
#2D array
array=np.zeros((5,5), dtype=int)
array[0, :]=1
array[-1, :]=1
array[:, 0]=1
array[:, -1]=1
print(array)



[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#9
import numpy as np

# Create an 8x8 matrix
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[1::2, ::2] = 1  # Fill 1 on odd rows, even columns
checkerboard[::2, 1::2] = 1  # Fill 1 on even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#problem_3_array_operations
#1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print("Addition: ", np.add(x,y))

Addition:  [[ 6  8]
 [10 13]]


In [ ]:
#2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print("Subtraction: ",np.subtract(x,y))


Subtraction:  [[-4 -4]
 [-4 -3]]


In [ ]:
#3
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
#multiplying array by any integer
multi= np.multiply(v,4)
multi_w=np.multiply(w,6)
print("v being multiplied by 4: ",multi)
print("w being multiplied by 6: ",multi_w)


v being multiplied by 4:  [36 40]
w being multiplied by 6:  [66 72]


In [ ]:
#4
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
square = np.square(v)
square_w=np.square(w)
print(square)
print(square_w)


[ 81 100]
[121 144]


In [ ]:
#5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

v_and_w= np.dot(v,w)
x_and_y= np.dot(x,y)
x_and_v= np.dot(x,v)
print("dot produxt of v and w: ",v_and_w)
print("dot product of x and y: ",x_and_y)
print("dot product of x and v: ",x_and_v)


dot produxt of v and w:  219
dot product of x and y:  [[19 22]
 [50 58]]
dot product of x and v:  [29 77]


In [ ]:
#6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#concatenate x and y along rows (axis=0)
con_xy_row= np.concatenate((x,y),axis=0)
#concatenate v and w along colums( reshape)
con_vw_col= np.stack((v,w))

print("Concatenate x and y along rows; ",con_xy_row)
print("Concatenate v and w along colums: ",con_vw_col)

Concatenate x and y along rows;  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along colums:  [[ 9 10]
 [11 12]]


In [ ]:
#7
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concat_xv=np.concatenate(x,v)
print(concat_xv)

#got error as the dimensions along the axis we're concatinating must match.


TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
#Problem - 4: Matrix Operations:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
print("Multiplication of A and inverse of A):")
print(np.dot(A, A_inv))
print("\nIdentity matrix:")
print(I)

# 2. Prove AB ≠ BA
AB = np.dot(A,B)
print("A.B : \n", AB, "\n")
BA = np.dot(B,A)
print("B.A : \n", BA, "\n")
print("AB == BA ? : ", np.allclose(AB,BA), "\n")

# 3. Prove (AB)ᵀ = BᵀAᵀ
trans_of_AB = np.transpose(AB)
print("Transpose of AB: \n",trans_of_AB, "\n")
trans_of_B = np.transpose(B)
trans_of_A = np.transpose(A)
A_trans_b_trans = np.dot(trans_of_B, trans_of_A)
print("A transpose.B transpose : \n", A_trans_b_trans, "\n")
print("Is (AB)ᵀ equal to BᵀAᵀ ?: ", np.allclose(trans_of_AB, A_trans_b_trans), "\n")

Multiplication of A and inverse of A):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix:
[[1. 0.]
 [0. 1.]]
A.B : 
 [[23 13]
 [51 29]] 

B.A : 
 [[36 44]
 [13 16]] 

AB == BA ? :  False 

Transpose of AB: 
 [[23 51]
 [13 29]] 

A transpose.B transpose : 
 [[23 51]
 [13 29]] 

Is (AB)ᵀ equal to BᵀAᵀ ?:  True 



In [9]:
# Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Step 1: Determinant of A
det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

# Step 2: Cofactor matrix
cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])

Determinant of A: -19


In [ ]:
# Solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# X = A⁻¹B
X = np.dot(A_inv, B)

print("Inverse of A:\n", A_inv)
print("\nSolution (x, y, z):", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
# 4.2 Experiment: How Fast is Numpy?

# 1. Element-wise Addition:

import time

list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("1. Element-wise Addition: \n")
start_at = time.time()
sum1 = [list1[i] + list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
sum2 = arr1 + arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds.")

1. Element-wise Addition: 

Time taken for this operation using Python Lists is:  0.016560077667236328 seconds.

Time taken for this operation using NumPy Arrays is: 0.006669759750366211 seconds.


In [ ]:
# 2. Element-wise Multiplication:

list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("Element-wise Multiplicatio: \n")
start_at = time.time()
product1 = [list1[i] * list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = arr1*arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds")

Element-wise Multiplicatio: 

Time taken for this operation using Python Lists is:  0.017018556594848633 seconds.

Time taken for this operation using NumPy Arrays is: 0.004713773727416992 seconds


In [ ]:
# 3. Dot Product :
list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("Dot product: \n")
start_at = time.time()
product1 = [list1[i] * list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = np.dot(arr1, arr2)
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Dot product: 

Time taken for this operation using Python Lists is:  0.015895843505859375 seconds.

Time taken using NumPy arrays: 0.0013651847839355469 seconds


In [ ]:
# 4. Matrix Multiplication
print("4. Matrix Multiplication")
size = 100

# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[j for j in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")

4. Matrix Multiplication
Time taken by Python Lists: 0.11701 seconds
Time taken by numpy: 0.00136 seconds
